#
# mozaik generic demo dashboard
#
# It's not required, but you should add this env var,
# without it, you'll probably reach the API rate limit.
#
# GITHUB_API_TOKEN=xxxxx
#
host: 127.0.0.1
port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 10000
# define the interval used by Mozaïk Bus to call registered APIs
apisPollInterval: 100000

dashboards:
- columns: 4
  rows:    3
  title:   AMO Dashboard
  widgets:

  - extension:    github
    widget:       Status
    columns:      1
    rows:         1
    x:            0
    y:            2

  - extension:    travis
    widget:       Repository
    owner:        mozilla
    repository:   addons-server
    columns:      1
    rows:         1
    x:            0
    y:            0

  - extension:   travis
    widget:      BuildHistogram
    owner:       mozilla
    repository:  addons-server
    columns:     2
    rows:        1
    x:           1
    y:           2

  - extension:   travis
    widget:      BuildHistory
    owner:       mozilla
    repository:  addons-server
    columns:     1
    rows:        3
    x:           3
    y:           0
